'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace com.logytechmobile.apps
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WsOfficeTrackSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class WsOfficeTrack
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private NotificacionOfficeTrackOperationCompleted As System.Threading.SendOrPostCallback
        
        Private NotificacionOfficeTrackSalidaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.ILSBusinessLayer.My.MySettings.Default.ILSBusinessLayer_com_logytechmobile_apps_WsOfficeTrack
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event NotificacionOfficeTrackCompleted As NotificacionOfficeTrackCompletedEventHandler
        
        '''<remarks/>
        Public Event NotificacionOfficeTrackSalidaCompleted As NotificacionOfficeTrackSalidaCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotificacionOfficeTrack", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function NotificacionOfficeTrack(ByVal Data As String) As String
            Dim results() As Object = Me.Invoke("NotificacionOfficeTrack", New Object() {Data})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub NotificacionOfficeTrackAsync(ByVal Data As String)
            Me.NotificacionOfficeTrackAsync(Data, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub NotificacionOfficeTrackAsync(ByVal Data As String, ByVal userState As Object)
            If (Me.NotificacionOfficeTrackOperationCompleted Is Nothing) Then
                Me.NotificacionOfficeTrackOperationCompleted = AddressOf Me.OnNotificacionOfficeTrackOperationCompleted
            End If
            Me.InvokeAsync("NotificacionOfficeTrack", New Object() {Data}, Me.NotificacionOfficeTrackOperationCompleted, userState)
        End Sub
        
        Private Sub OnNotificacionOfficeTrackOperationCompleted(ByVal arg As Object)
            If (Not (Me.NotificacionOfficeTrackCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent NotificacionOfficeTrackCompleted(Me, New NotificacionOfficeTrackCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotificacionOfficeTrackSalida", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function NotificacionOfficeTrackSalida(ByVal xml As String) As String
            Dim results() As Object = Me.Invoke("NotificacionOfficeTrackSalida", New Object() {xml})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub NotificacionOfficeTrackSalidaAsync(ByVal xml As String)
            Me.NotificacionOfficeTrackSalidaAsync(xml, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub NotificacionOfficeTrackSalidaAsync(ByVal xml As String, ByVal userState As Object)
            If (Me.NotificacionOfficeTrackSalidaOperationCompleted Is Nothing) Then
                Me.NotificacionOfficeTrackSalidaOperationCompleted = AddressOf Me.OnNotificacionOfficeTrackSalidaOperationCompleted
            End If
            Me.InvokeAsync("NotificacionOfficeTrackSalida", New Object() {xml}, Me.NotificacionOfficeTrackSalidaOperationCompleted, userState)
        End Sub
        
        Private Sub OnNotificacionOfficeTrackSalidaOperationCompleted(ByVal arg As Object)
            If (Not (Me.NotificacionOfficeTrackSalidaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent NotificacionOfficeTrackSalidaCompleted(Me, New NotificacionOfficeTrackSalidaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub NotificacionOfficeTrackCompletedEventHandler(ByVal sender As Object, ByVal e As NotificacionOfficeTrackCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class NotificacionOfficeTrackCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub NotificacionOfficeTrackSalidaCompletedEventHandler(ByVal sender As Object, ByVal e As NotificacionOfficeTrackSalidaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class NotificacionOfficeTrackSalidaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
