'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.4952
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class DetalleOrdenRecepcionMerchandising

    '''<summary>
    '''Control form1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''Control smAjaxManager.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents smAjaxManager As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''Control upGeneral.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents upGeneral As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Control epNotificador.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents epNotificador As Global.BPColSysOP.EncabezadoPagina

    '''<summary>
    '''Control pnlGeneral.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents pnlGeneral As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Control lblOrdenRecepcion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblOrdenRecepcion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblFechaRecepcion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblFechaRecepcion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblProveedor.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblProveedor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblRemision.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblRemision As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblTipoProducto.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblTipoProducto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblTipoRecepcion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblTipoRecepcion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblConsignado.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblConsignado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblDestinatario.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblDestinatario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control fOrdenCompra.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents fOrdenCompra As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Control lblOrdenCompra.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblOrdenCompra As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblEstadoOrden.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblEstadoOrden As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control trDistribucionPorRegiones.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents trDistribucionPorRegiones As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Control gvDistribucion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents gvDistribucion As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Control lblCantidadTotal.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblCantidadTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblCantidadRecibida.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblCantidadRecibida As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbCerrarOrden.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbCerrarOrden As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Control hfIdTipoProducto.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents hfIdTipoProducto As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Control hfIdOrdenCompra.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents hfIdOrdenCompra As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Control hfIdEstadoOrdenRecepcion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents hfIdEstadoOrdenRecepcion As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Control hfIdOrdenRecepcion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents hfIdOrdenRecepcion As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Control hfCantidadPermitida.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents hfCantidadPermitida As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Control hfCantidadPalletRegistrada.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents hfCantidadPalletRegistrada As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Control EncabezadoPagina1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents EncabezadoPagina1 As Global.BPColSysOP.EncabezadoPagina

    '''<summary>
    '''Control epAuxNotificacion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents epAuxNotificacion As Global.BPColSysOP.EncabezadoPagina

    '''<summary>
    '''Control pnlCreacionPallet.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents pnlCreacionPallet As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Control trPeso.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents trPeso As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Control txtPeso.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtPeso As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control lblFormato.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblFormato As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control rfvPeso.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvPeso As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control revPeso.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents revPeso As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''Control txtObservacion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtObservacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control revObservacion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents revObservacion As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''Control cblNovedad.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cblNovedad As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''Control hfFlagFiltradoMaterial.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents hfFlagFiltradoMaterial As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Control txtFiltroMaterial.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtFiltroMaterial As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control upProducto.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents upProducto As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Control ddlMaterial.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents ddlMaterial As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control rfvProducto.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvProducto As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control hfCantidadDisponible.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents hfCantidadDisponible As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Control ddlRegion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents ddlRegion As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control rfvRegion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvRegion As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control txtCantidad.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtCantidad As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rfvCantidad.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvCantidad As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control revCantidad.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents revCantidad As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''Control lbAdicionarCaja.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbAdicionarCaja As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Control gvCajas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents gvCajas As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Control lbCrearPallet.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbCrearPallet As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Control pnlProductoAdicional.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents pnlProductoAdicional As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control trProductoAdicional.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents trProductoAdicional As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Control ddlProductoAdicional.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents ddlProductoAdicional As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control lblCantidadAdicional.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblCantidadAdicional As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control rfvProductoAdicional.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvProductoAdicional As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control txtCantidadAdicional.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtCantidadAdicional As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rfvCantidadAdicional.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvCantidadAdicional As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control revCantidadAdicional.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents revCantidadAdicional As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''Control lnkAgregarProductoAdicional.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lnkAgregarProductoAdicional As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Control gvProductoAdicional.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents gvProductoAdicional As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Control hfTotalProductoAdicional.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents hfTotalProductoAdicional As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Control tblCrearPalletAdicional.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tblCrearPalletAdicional As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Control txtPesoPalletAdicionl.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtPesoPalletAdicionl As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rfvPesoPalletAdicional.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvPesoPalletAdicional As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control revPesoPalletAdicional.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents revPesoPalletAdicional As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''Control lnkCrearPalletProAdicional.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lnkCrearPalletProAdicional As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Control gvPallets.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents gvPallets As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Control tblPalletsProductoAdicional.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tblPalletsProductoAdicional As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Control gvPalletProductoAdicional.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents gvPalletProductoAdicional As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Control ModalProgress1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents ModalProgress1 As Global.BPColSysOP.ModalProgress
End Class
