'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DetalleOrdenRecepcionGeneral

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''smAjaxManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents smAjaxManager As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''upGeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upGeneral As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''epNotificador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents epNotificador As Global.BPColSysOP.EncabezadoPagina

    '''<summary>
    '''pnlGeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGeneral As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblOrdenRecepcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrdenRecepcion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFechaRecepcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFechaRecepcion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOrdenCompra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrdenCompra As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRemision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRemision As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTipoProducto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTipoProducto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTipoRecepcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTipoRecepcion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblConsignado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConsignado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDestinatario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDestinatario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEstadoOrden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEstadoOrden As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCantidadTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCantidadTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trDistribucionPorRegiones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trDistribucionPorRegiones As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''gvDistribucion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDistribucion As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblCantidadRecibida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCantidadRecibida As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BtnCerrarRecepcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCerrarRecepcion As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hfIdTipoProducto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIdTipoProducto As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfIdOrdenRecepcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIdOrdenRecepcion As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfIdOrdenCompra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIdOrdenCompra As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfIdEstadoOrdenRecepcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIdEstadoOrdenRecepcion As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfCantidadPermitida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCantidadPermitida As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfCantidadPalletRegistrada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCantidadPalletRegistrada As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfCantidadCajaEmpaqueTemporal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCantidadCajaEmpaqueTemporal As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''epAuxNotificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents epAuxNotificacion As Global.BPColSysOP.EncabezadoPagina

    '''<summary>
    '''pnlCreacionPallet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCreacionPallet As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''trPeso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trPeso As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtPeso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPeso As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblFormato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFormato As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rfvPeso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvPeso As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''revPeso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revPeso As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtObservacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObservacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revObservacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revObservacion As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''cblNovedad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblNovedad As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''hfFlagFiltradoMaterial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfFlagFiltradoMaterial As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtFiltroMaterial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFiltroMaterial As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlMaterial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMaterial As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblCantidadMateriales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCantidadMateriales As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rfvProducto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvProducto As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''hfCantidadDisponible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCantidadDisponible As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ddlRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRegion As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvRegion As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtCantidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCantidad As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvCantidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCantidad As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''revCantidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revCantidad As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbAdicionarCaja control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbAdicionarCaja As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''gvCajas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvCajas As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lbCrearPallet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCrearPallet As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''tblProductoAdicional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblProductoAdicional As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''trProductoAdicional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trProductoAdicional As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ddlProductoAdicional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProductoAdicional As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblCantidadAdicional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCantidadAdicional As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rfvProductoAdicional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvProductoAdicional As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtCantidadAdicional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCantidadAdicional As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvCantidadAdicional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCantidadAdicional As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''revCantidadAdicional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revCantidadAdicional As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lnkAgregarProductoAdicional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAgregarProductoAdicional As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''upActulizacionGrillaProductoAdicional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upActulizacionGrillaProductoAdicional As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''gvProductoAdicional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvProductoAdicional As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''hfTotalProductoAdicional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfTotalProductoAdicional As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''tblCrearPalletAdicional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblCrearPalletAdicional As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''txtPesoPalletAdicionl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPesoPalletAdicionl As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvPesoPalletAdicional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvPesoPalletAdicional As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''revPesoPalletAdicional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revPesoPalletAdicional As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''cvPesoPalletAdicional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvPesoPalletAdicional As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''lnkCrearPalletProAdicional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCrearPalletProAdicional As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''gvPallets control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvPallets As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tblPalletsProductoAdicional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblPalletsProductoAdicional As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''gvPalletProductoAdicional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvPalletProductoAdicional As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ModalProgress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalProgress1 As Global.BPColSysOP.ModalProgress
End Class
