Public Class MapFields

    Public Property SourceIdField As String
    Public Property NameField As String
    Public Property TimeZoneType As Integer
    Public Property TimeZone As String
    Public Property DefaultTimeZone As String
    Public Property PhoneField As String
    Public Property PhoneDescription As Integer
    Public Property PhoneTimeZoneType As Integer
    Public Property PhoneTimeZone As String
    Public Property PhoneField2 As String
    Public Property PhoneDescription2 As Integer
    Public Property PhoneTimeZoneType2 As Integer
    Public Property PhoneTimeZone2 As String
    Public Property PhoneField3 As String
    Public Property PhoneDescription3 As Integer
    Public Property PhoneTimeZoneType3 As Integer
    Public Property PhoneTimeZone3 As String
    Public Property PhoneField4 As String
    Public Property PhoneDescription4 As Integer
    Public Property PhoneTimeZoneType4 As Integer
    Public Property PhoneTimeZone4 As String
    Public Property PhoneField5 As String
    Public Property PhoneDescription5 As Integer
    Public Property PhoneTimeZoneType5 As Integer
    Public Property PhoneTimeZone5 As String
    Public Property PhoneField6 As String
    Public Property PhoneDescription6 As Integer
    Public Property PhoneTimeZoneType6 As Integer
    Public Property PhoneTimeZone6 As String
    Public Property PhoneField7 As String
    Public Property PhoneDescription7 As Integer
    Public Property PhoneTimeZoneType7 As Integer
    Public Property PhoneTimeZone7 As String
    Public Property PhoneField8 As String
    Public Property PhoneDescription8 As Integer
    Public Property PhoneTimeZoneType8 As Integer
    Public Property PhoneTimeZone8 As String
    Public Property PhoneField9 As String
    Public Property PhoneDescription9 As Integer
    Public Property PhoneTimeZoneType9 As Integer
    Public Property PhoneTimeZone9 As String
    Public Property PhoneField10 As String
    Public Property PhoneDescription10 As Integer
    Public Property PhoneTimeZoneType10 As Integer
    Public Property PhoneTimeZone10 As String
    Public Property CommentsField As String
    Public Property CustomDataField1 As String
    Public Property CustomDataField2 As String
    Public Property CustomDataField3 As String
    Public Property CallerIdField As String
    Public Property CallerNameField As String
    Public Property Filter As String
End Class
