'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace NotusExpressDaviviendaService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="NotusExpressDaviviendaWebServiceSoap", [Namespace]:="http://www.logytechmobile.com/NotusExpressWebService/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Object()))>  _
    Partial Public Class NotusExpressDaviviendaWebService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ActualizaGestionVentaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RegistraSerialGestionVentaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RegistraCampaniaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ActualizaCampaniaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.ILSBusinessLayer.My.MySettings.Default.ILSBusinessLayer_NotusExpressDaviviendaService_NotusExpressDaviviendaWebService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ActualizaGestionVentaCompleted As ActualizaGestionVentaCompletedEventHandler
        
        '''<remarks/>
        Public Event RegistraSerialGestionVentaCompleted As RegistraSerialGestionVentaCompletedEventHandler
        
        '''<remarks/>
        Public Event RegistraCampaniaCompleted As RegistraCampaniaCompletedEventHandler
        
        '''<remarks/>
        Public Event ActualizaCampaniaCompleted As ActualizaCampaniaCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.logytechmobile.com/NotusExpressWebService/ActualizaGestionVenta", RequestNamespace:="http://www.logytechmobile.com/NotusExpressWebService/", ResponseNamespace:="http://www.logytechmobile.com/NotusExpressWebService/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ActualizaGestionVenta(ByVal infoGestion As WsGestionVenta) As ResultadoProceso
            Dim results() As Object = Me.Invoke("ActualizaGestionVenta", New Object() {infoGestion})
            Return CType(results(0),ResultadoProceso)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ActualizaGestionVentaAsync(ByVal infoGestion As WsGestionVenta)
            Me.ActualizaGestionVentaAsync(infoGestion, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ActualizaGestionVentaAsync(ByVal infoGestion As WsGestionVenta, ByVal userState As Object)
            If (Me.ActualizaGestionVentaOperationCompleted Is Nothing) Then
                Me.ActualizaGestionVentaOperationCompleted = AddressOf Me.OnActualizaGestionVentaOperationCompleted
            End If
            Me.InvokeAsync("ActualizaGestionVenta", New Object() {infoGestion}, Me.ActualizaGestionVentaOperationCompleted, userState)
        End Sub
        
        Private Sub OnActualizaGestionVentaOperationCompleted(ByVal arg As Object)
            If (Not (Me.ActualizaGestionVentaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ActualizaGestionVentaCompleted(Me, New ActualizaGestionVentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.logytechmobile.com/NotusExpressWebService/RegistraSerialGestionVenta", RequestNamespace:="http://www.logytechmobile.com/NotusExpressWebService/", ResponseNamespace:="http://www.logytechmobile.com/NotusExpressWebService/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RegistraSerialGestionVenta(ByVal idServicio As Integer, ByVal dsDatos As System.Data.DataSet) As ResultadoProceso
            Dim results() As Object = Me.Invoke("RegistraSerialGestionVenta", New Object() {idServicio, dsDatos})
            Return CType(results(0),ResultadoProceso)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RegistraSerialGestionVentaAsync(ByVal idServicio As Integer, ByVal dsDatos As System.Data.DataSet)
            Me.RegistraSerialGestionVentaAsync(idServicio, dsDatos, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegistraSerialGestionVentaAsync(ByVal idServicio As Integer, ByVal dsDatos As System.Data.DataSet, ByVal userState As Object)
            If (Me.RegistraSerialGestionVentaOperationCompleted Is Nothing) Then
                Me.RegistraSerialGestionVentaOperationCompleted = AddressOf Me.OnRegistraSerialGestionVentaOperationCompleted
            End If
            Me.InvokeAsync("RegistraSerialGestionVenta", New Object() {idServicio, dsDatos}, Me.RegistraSerialGestionVentaOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegistraSerialGestionVentaOperationCompleted(ByVal arg As Object)
            If (Not (Me.RegistraSerialGestionVentaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegistraSerialGestionVentaCompleted(Me, New RegistraSerialGestionVentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.logytechmobile.com/NotusExpressWebService/RegistraCampania", RequestNamespace:="http://www.logytechmobile.com/NotusExpressWebService/", ResponseNamespace:="http://www.logytechmobile.com/NotusExpressWebService/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RegistraCampania(ByVal infoCampania As WsRegistroCampania) As ResultadoProceso
            Dim results() As Object = Me.Invoke("RegistraCampania", New Object() {infoCampania})
            Return CType(results(0),ResultadoProceso)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RegistraCampaniaAsync(ByVal infoCampania As WsRegistroCampania)
            Me.RegistraCampaniaAsync(infoCampania, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegistraCampaniaAsync(ByVal infoCampania As WsRegistroCampania, ByVal userState As Object)
            If (Me.RegistraCampaniaOperationCompleted Is Nothing) Then
                Me.RegistraCampaniaOperationCompleted = AddressOf Me.OnRegistraCampaniaOperationCompleted
            End If
            Me.InvokeAsync("RegistraCampania", New Object() {infoCampania}, Me.RegistraCampaniaOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegistraCampaniaOperationCompleted(ByVal arg As Object)
            If (Not (Me.RegistraCampaniaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegistraCampaniaCompleted(Me, New RegistraCampaniaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.logytechmobile.com/NotusExpressWebService/ActualizaCampania", RequestNamespace:="http://www.logytechmobile.com/NotusExpressWebService/", ResponseNamespace:="http://www.logytechmobile.com/NotusExpressWebService/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ActualizaCampania(ByVal infoCampania As WsRegistroCampania) As ResultadoProceso
            Dim results() As Object = Me.Invoke("ActualizaCampania", New Object() {infoCampania})
            Return CType(results(0),ResultadoProceso)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ActualizaCampaniaAsync(ByVal infoCampania As WsRegistroCampania)
            Me.ActualizaCampaniaAsync(infoCampania, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ActualizaCampaniaAsync(ByVal infoCampania As WsRegistroCampania, ByVal userState As Object)
            If (Me.ActualizaCampaniaOperationCompleted Is Nothing) Then
                Me.ActualizaCampaniaOperationCompleted = AddressOf Me.OnActualizaCampaniaOperationCompleted
            End If
            Me.InvokeAsync("ActualizaCampania", New Object() {infoCampania}, Me.ActualizaCampaniaOperationCompleted, userState)
        End Sub
        
        Private Sub OnActualizaCampaniaOperationCompleted(ByVal arg As Object)
            If (Not (Me.ActualizaCampaniaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ActualizaCampaniaCompleted(Me, New ActualizaCampaniaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.logytechmobile.com/NotusExpressWebService/")>  _
    Partial Public Class WsGestionVenta
        
        Private idGestionVentaField As Long
        
        Private idClienteField As Integer
        
        Private idResultadoProcesoField As ResuladoProcesoVenta
        
        Private idEstadoField As EstadosGestionDeVenta
        
        Private observacionCallCenterField As String
        
        Private observacionVendedorField As String
        
        Private fechaRecepcionDocumentosField As Date
        
        Private idReceptorDocumentoField As Integer
        
        Private fechaLegalizacionField As Date
        
        Private idLegalizadorField As Integer
        
        Private esNovedadField As Boolean
        
        Private observacionDeclinarField As String
        
        Private idNovedadField As Integer
        
        Private observacionNovedadField As String
        
        Private idCampaniaNotusField As Integer
        
        Private idServicioNotusField As Long
        
        Private idModificadorField As Integer
        
        Private fechaAgendaField As Date
        
        Private idEstadoServicioMensajeriaField As Integer
        
        Private listaNovedadesField() As Object
        
        '''<remarks/>
        Public Property IdGestionVenta() As Long
            Get
                Return Me.idGestionVentaField
            End Get
            Set
                Me.idGestionVentaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdCliente() As Integer
            Get
                Return Me.idClienteField
            End Get
            Set
                Me.idClienteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdResultadoProceso() As ResuladoProcesoVenta
            Get
                Return Me.idResultadoProcesoField
            End Get
            Set
                Me.idResultadoProcesoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdEstado() As EstadosGestionDeVenta
            Get
                Return Me.idEstadoField
            End Get
            Set
                Me.idEstadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ObservacionCallCenter() As String
            Get
                Return Me.observacionCallCenterField
            End Get
            Set
                Me.observacionCallCenterField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ObservacionVendedor() As String
            Get
                Return Me.observacionVendedorField
            End Get
            Set
                Me.observacionVendedorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaRecepcionDocumentos() As Date
            Get
                Return Me.fechaRecepcionDocumentosField
            End Get
            Set
                Me.fechaRecepcionDocumentosField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdReceptorDocumento() As Integer
            Get
                Return Me.idReceptorDocumentoField
            End Get
            Set
                Me.idReceptorDocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaLegalizacion() As Date
            Get
                Return Me.fechaLegalizacionField
            End Get
            Set
                Me.fechaLegalizacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdLegalizador() As Integer
            Get
                Return Me.idLegalizadorField
            End Get
            Set
                Me.idLegalizadorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EsNovedad() As Boolean
            Get
                Return Me.esNovedadField
            End Get
            Set
                Me.esNovedadField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ObservacionDeclinar() As String
            Get
                Return Me.observacionDeclinarField
            End Get
            Set
                Me.observacionDeclinarField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdNovedad() As Integer
            Get
                Return Me.idNovedadField
            End Get
            Set
                Me.idNovedadField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ObservacionNovedad() As String
            Get
                Return Me.observacionNovedadField
            End Get
            Set
                Me.observacionNovedadField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdCampaniaNotus() As Integer
            Get
                Return Me.idCampaniaNotusField
            End Get
            Set
                Me.idCampaniaNotusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdServicioNotus() As Long
            Get
                Return Me.idServicioNotusField
            End Get
            Set
                Me.idServicioNotusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdModificador() As Integer
            Get
                Return Me.idModificadorField
            End Get
            Set
                Me.idModificadorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaAgenda() As Date
            Get
                Return Me.fechaAgendaField
            End Get
            Set
                Me.fechaAgendaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdEstadoServicioMensajeria() As Integer
            Get
                Return Me.idEstadoServicioMensajeriaField
            End Get
            Set
                Me.idEstadoServicioMensajeriaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ListaNovedades() As Object()
            Get
                Return Me.listaNovedadesField
            End Get
            Set
                Me.listaNovedadesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.logytechmobile.com/NotusExpressWebService/")>  _
    Public Enum ResuladoProcesoVenta
        
        '''<remarks/>
        Aprobada
        
        '''<remarks/>
        Negada
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.logytechmobile.com/NotusExpressWebService/")>  _
    Public Enum EstadosGestionDeVenta
        
        '''<remarks/>
        RegistroParcial
        
        '''<remarks/>
        Registrada
        
        '''<remarks/>
        VentaDeclinada
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.logytechmobile.com/NotusExpressWebService/")>  _
    Partial Public Class WsRegistroCampania
        
        Private idCampaniaField As Integer
        
        Private nombreField As String
        
        Private fechaInicioField As Date
        
        Private fechaFinField As Date
        
        Private activoField As Boolean
        
        Private listCiudadesField() As Integer
        
        Private listBodegasField() As Integer
        
        Private listProductoExternoField() As Integer
        
        Private listDocumentoFinancieroField() As Integer
        
        Private listTiposDeServicioField() As Integer
        
        Private idClienteExternoField As Integer
        
        Private idTipoCampaniaField As Integer
        
        Private idSistemaField As Integer
        
        '''<remarks/>
        Public Property IdCampania() As Integer
            Get
                Return Me.idCampaniaField
            End Get
            Set
                Me.idCampaniaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaInicio() As Date
            Get
                Return Me.fechaInicioField
            End Get
            Set
                Me.fechaInicioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaFin() As Date
            Get
                Return Me.fechaFinField
            End Get
            Set
                Me.fechaFinField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Activo() As Boolean
            Get
                Return Me.activoField
            End Get
            Set
                Me.activoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ListCiudades() As Integer()
            Get
                Return Me.listCiudadesField
            End Get
            Set
                Me.listCiudadesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ListBodegas() As Integer()
            Get
                Return Me.listBodegasField
            End Get
            Set
                Me.listBodegasField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ListProductoExterno() As Integer()
            Get
                Return Me.listProductoExternoField
            End Get
            Set
                Me.listProductoExternoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ListDocumentoFinanciero() As Integer()
            Get
                Return Me.listDocumentoFinancieroField
            End Get
            Set
                Me.listDocumentoFinancieroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ListTiposDeServicio() As Integer()
            Get
                Return Me.listTiposDeServicioField
            End Get
            Set
                Me.listTiposDeServicioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdClienteExterno() As Integer
            Get
                Return Me.idClienteExternoField
            End Get
            Set
                Me.idClienteExternoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdTipoCampania() As Integer
            Get
                Return Me.idTipoCampaniaField
            End Get
            Set
                Me.idTipoCampaniaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdSistema() As Integer
            Get
                Return Me.idSistemaField
            End Get
            Set
                Me.idSistemaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.logytechmobile.com/NotusExpressWebService/")>  _
    Partial Public Class ResultadoProceso
        
        Private valorField As Long
        
        Private mensajeField As String
        
        '''<remarks/>
        Public Property Valor() As Long
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ActualizaGestionVentaCompletedEventHandler(ByVal sender As Object, ByVal e As ActualizaGestionVentaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ActualizaGestionVentaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResultadoProceso
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResultadoProceso)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub RegistraSerialGestionVentaCompletedEventHandler(ByVal sender As Object, ByVal e As RegistraSerialGestionVentaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RegistraSerialGestionVentaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResultadoProceso
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResultadoProceso)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub RegistraCampaniaCompletedEventHandler(ByVal sender As Object, ByVal e As RegistraCampaniaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RegistraCampaniaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResultadoProceso
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResultadoProceso)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ActualizaCampaniaCompletedEventHandler(ByVal sender As Object, ByVal e As ActualizaCampaniaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ActualizaCampaniaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResultadoProceso
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResultadoProceso)
            End Get
        End Property
    End Class
End Namespace
