'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidad para autoguardar My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://lmwebserver.logytechmobile.com/sid/WebService/SIDService.asmx")>  _
        Public ReadOnly Property ILSBusinessLayer_SIDService1_SIDService() As String
            Get
                Return CType(Me("ILSBusinessLayer_SIDService1_SIDService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://172.22.85.60:50000/WS_ADICION_DECLARACION_LG/Config1?style=document")>  _
        Public ReadOnly Property ILSBusinessLayer_SAPAdicionDeclaracion_WS_ADICION_DECLARACION_LG() As String
            Get
                Return CType(Me("ILSBusinessLayer_SAPAdicionDeclaracion_WS_ADICION_DECLARACION_LG"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://172.22.85.60:50000/WS_INV_ENTREGA_LG/Config1?style=document")>  _
        Public ReadOnly Property ILSBusinessLayer_SAPConsultarEntrega_WS_INV_ENTREGA_LG() As String
            Get
                Return CType(Me("ILSBusinessLayer_SAPConsultarEntrega_WS_INV_ENTREGA_LG"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://172.22.85.60:50000/WS_INVENTARIO_LG/Config1?style=document")>  _
        Public ReadOnly Property ILSBusinessLayer_SAPConsultarInventario_WS_INVENTARIO_LG() As String
            Get
                Return CType(Me("ILSBusinessLayer_SAPConsultarInventario_WS_INVENTARIO_LG"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://172.22.85.60:50000/WS_INV_SERIALES_LG/Config1?style=document")>  _
        Public ReadOnly Property ILSBusinessLayer_SapConsultarSerial_WS_INV_SERIALES_LG() As String
            Get
                Return CType(Me("ILSBusinessLayer_SapConsultarSerial_WS_INV_SERIALES_LG"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://172.22.85.60:50000/WS_ENTRADAS_LG/Config1?style=document")>  _
        Public ReadOnly Property ILSBusinessLayer_SAPContabilizacionEntrada_WS_ENTRADAS_LG() As String
            Get
                Return CType(Me("ILSBusinessLayer_SAPContabilizacionEntrada_WS_ENTRADAS_LG"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://172.22.85.60:50000/WS_PDF_LG/Config1?style=document")>  _
        Public ReadOnly Property ILSBusinessLayer_SAPImpresionDocumentos_WS_PDF_LG() As String
            Get
                Return CType(Me("ILSBusinessLayer_SAPImpresionDocumentos_WS_PDF_LG"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://172.22.85.60:50000/WS_MAESTRO_CENTRO_LG/Config1?style=document")>  _
        Public ReadOnly Property ILSBusinessLayer_SAPMaestroAlmacenes_WS_MAESTRO_CENTRO_LG() As String
            Get
                Return CType(Me("ILSBusinessLayer_SAPMaestroAlmacenes_WS_MAESTRO_CENTRO_LG"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://172.22.85.60:50000/WS_PEDIDOS_LG/Config1?style=document")>  _
        Public ReadOnly Property ILSBusinessLayer_SapPoolPedidos_WS_PEDIDOS_LG() As String
            Get
                Return CType(Me("ILSBusinessLayer_SapPoolPedidos_WS_PEDIDOS_LG"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://172.22.85.60:50000/WS_CAPSER_LG/Config1?style=document")>  _
        Public ReadOnly Property ILSBusinessLayer_SAPZmmCapser_WS_CAPSER_LG() As String
            Get
                Return CType(Me("ILSBusinessLayer_SAPZmmCapser_WS_CAPSER_LG"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://lmwebserver.logytechmobile.com/sid/WebService/SIDService.asmx")>  _
        Public ReadOnly Property ILSBusinessLayer_SIDService_SIDService() As String
            Get
                Return CType(Me("ILSBusinessLayer_SIDService_SIDService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://colbogsa025.logytechmobile.com/NotusExpressDavivienda/WebService/NotusExpr"& _ 
            "essService.asmx")>  _
        Public ReadOnly Property ILSBusinessLayer_NotusExpressService_NotusExpressService() As String
            Get
                Return CType(Me("ILSBusinessLayer_NotusExpressService_NotusExpressService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://apps.logytechmobile.com/NotusExpress.Bancolombia/WebService/NotusExpressBa"& _ 
            "ncolombiaService.asmx")>  _
        Public ReadOnly Property ILSBusinessLayer_NotusExpressBancolombiaService_NotusExpressBancolombiaService() As String
            Get
                Return CType(Me("ILSBusinessLayer_NotusExpressBancolombiaService_NotusExpressBancolombiaService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://appsfin.logytechmobile.com/NotusExpress.Davivienda/WebService/NotusExpress"& _ 
            "DaviviendaWebService.asmx")>  _
        Public ReadOnly Property ILSBusinessLayer_NotusExpressDaviviendaService_NotusExpressDaviviendaWebService() As String
            Get
                Return CType(Me("ILSBusinessLayer_NotusExpressDaviviendaService_NotusExpressDaviviendaWebService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://appsfin.logytechmobile.com/notusexpress.daviviendasamsung/webservice/Notus"& _ 
            "ExpressDavSamService.asmx")>  _
        Public ReadOnly Property ILSBusinessLayer_NotusExpressDavSamService_NotusExpressService() As String
            Get
                Return CType(Me("ILSBusinessLayer_NotusExpressDavSamService_NotusExpressService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://latam.officetrack.com/services/TaskManagement.asmx")>  _
        Public ReadOnly Property ILSBusinessLayer_com_officetrack_latam_TaskManagement() As String
            Get
                Return CType(Me("ILSBusinessLayer_com_officetrack_latam_TaskManagement"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://apps.logytechmobile.com/NotusCemOfficeTrackWS/WsOfficeTrack.asmx")>  _
        Public ReadOnly Property ILSBusinessLayer_com_logytechmobile_apps_WsOfficeTrack() As String
            Get
                Return CType(Me("ILSBusinessLayer_com_logytechmobile_apps_WsOfficeTrack"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.ILSBusinessLayer.My.MySettings
            Get
                Return Global.ILSBusinessLayer.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
